import { bigint, boolean, char, integer, jsonb, pgEnum, pgTable, smallint, text, time, timestamp, uniqueIndex, uuid, index } from 'drizzle-orm/pg-core';

const timestamptz = { withTimezone: true } as const;

export const bookingStatus = pgEnum('booking_status', ['pending', 'confirmed', 'cancelled', 'completed', 'no_show']);
export const bookingSlotStatus = pgEnum('booking_slot_status', ['available', 'held', 'booked', 'blocked']);
export const attendeeRole = pgEnum('attendee_role', ['host', 'customer', 'additional']);
export const calendarSyncStatus = pgEnum('calendar_sync_status', ['pending', 'synced', 'cancelled', 'failed']);
export const reservationStatus = pgEnum('reservation_status', ['active', 'expired', 'released', 'consumed']);
export const paymentStatus = pgEnum('payment_status', ['pending', 'authorized', 'paid', 'failed', 'refunded', 'partially_refunded']);
export const fulfillmentState = pgEnum('fulfillment_state', ['unfulfilled', 'processing', 'fulfilled', 'cancelled', 'returned']);
export const inventoryMovementType = pgEnum('inventory_movement_type', ['receipt', 'adjustment', 'reservation', 'reservation_release', 'sale', 'return', 'correction']);
export const orderStatus = pgEnum('order_status', ['pending_payment', 'paid', 'payment_failed', 'cancelled', 'refunded']);
export const orderState = pgEnum('order_state', ['pending', 'paid', 'processing', 'fulfilled', 'cancelled', 'refunded', 'payment_failed']);
export const fulfillmentStatus = pgEnum('fulfillment_status', ['unfulfilled', 'processing', 'fulfilled', 'cancelled']);
export const subscriptionStatus = pgEnum('subscription_status', ['trialing', 'active', 'past_due', 'cancelled', 'incomplete', 'paused']);
export const integrationStatus = pgEnum('integration_status', ['connected', 'disconnected', 'error']);
export const idempotencyStatus = pgEnum('idempotency_status', ['processing', 'completed', 'failed']);
export const entitlementState = pgEnum('entitlement_state', ['free', 'trial', 'active', 'grace_period', 'past_due', 'cancellation_scheduled', 'subscription_ending', 'pending', 'failed_payment', 'canceled']);
export const webhookProcessingStatus = pgEnum('webhook_processing_status', ['received', 'processing', 'processed', 'failed']);

export const appUsers = pgTable('app_users', { id: uuid('id').defaultRandom().primaryKey(), externalAuthId: text('external_auth_id').notNull().unique(), email: text('email'), displayName: text('display_name'), createdAt: timestamp('created_at', timestamptz).defaultNow().notNull(), updatedAt: timestamp('updated_at', timestamptz).defaultNow().notNull() });
export const accounts = pgTable('accounts', { id: uuid('id').defaultRandom().primaryKey(), primaryUserId: uuid('primary_user_id').notNull().references(() => appUsers.id), name: text('name').notNull(), createdAt: timestamp('created_at', timestamptz).defaultNow().notNull(), updatedAt: timestamp('updated_at', timestamptz).defaultNow().notNull() }, (table) => ({ primaryUserIndex: index('accounts_primary_user_idx').on(table.primaryUserId, table.createdAt) }));
export const accountMemberships = pgTable('account_memberships', { accountId: uuid('account_id').notNull().references(() => accounts.id), userId: uuid('user_id').notNull().references(() => appUsers.id), role: text('role').notNull(), createdAt: timestamp('created_at', timestamptz).defaultNow().notNull(), updatedAt: timestamp('updated_at', timestamptz).defaultNow().notNull() }, (table) => ({ membershipKey: uniqueIndex('account_memberships_key').on(table.accountId, table.userId), userIndex: index('account_memberships_user_idx').on(table.userId, table.accountId) }));
export const sites = pgTable('sites', { id: uuid('id').defaultRandom().primaryKey(), accountId: uuid('account_id').references(() => accounts.id), legacySiteId: text('legacy_site_id'), ownerUserId: uuid('owner_user_id').notNull().references(() => appUsers.id), handle: text('handle').notNull().unique(), displayName: text('display_name').notNull(), content: jsonb('content').$type<Record<string, unknown>>().notNull().default({}), isPublished: boolean('is_published').notNull().default(false), publishedAt: timestamp('published_at', timestamptz), createdAt: timestamp('created_at', timestamptz).defaultNow().notNull(), updatedAt: timestamp('updated_at', timestamptz).defaultNow().notNull() }, (table) => ({ publishedHandleIndex: index('sites_published_handle_idx').on(table.handle), ownerUpdatedIndex: index('sites_owner_updated_idx').on(table.ownerUserId, table.updatedAt), accountUpdatedIndex: index('sites_account_updated_idx').on(table.accountId, table.updatedAt), legacySiteIndex: uniqueIndex('sites_legacy_site_idx').on(table.legacySiteId) }));

export const bookingServices = pgTable('booking_services', { id: uuid('id').defaultRandom().primaryKey(), siteId: uuid('site_id').notNull().references(() => sites.id), legacyServiceId: text('legacy_service_id'), slug: text('slug').notNull(), name: text('name').notNull(), description: text('description'), durationMinutes: integer('duration_minutes').notNull(), bufferMinutes: integer('buffer_minutes').notNull().default(0), createdAt: timestamp('created_at', timestamptz).defaultNow().notNull(), updatedAt: timestamp('updated_at', timestamptz).defaultNow().notNull() }, (table) => ({ siteSlug: uniqueIndex('booking_services_site_slug').on(table.siteId, table.slug), legacyKey: uniqueIndex('booking_services_legacy_service_idx').on(table.siteId, table.legacyServiceId) }));
export const availabilityRules = pgTable('availability_rules', { id: uuid('id').defaultRandom().primaryKey(), siteId: uuid('site_id').notNull().references(() => sites.id), weekday: smallint('weekday').notNull(), startsAt: time('starts_at').notNull(), endsAt: time('ends_at').notNull(), timezone: text('timezone').notNull() }, (table) => ({ siteWeekday: index('availability_rules_site_weekday_idx').on(table.siteId, table.weekday, table.startsAt) }));
export const availabilityExceptions = pgTable('availability_exceptions', { id: uuid('id').defaultRandom().primaryKey(), siteId: uuid('site_id').notNull().references(() => sites.id), startsAt: timestamp('starts_at', timestamptz).notNull(), endsAt: timestamp('ends_at', timestamptz).notNull(), reason: text('reason') }, (table) => ({ siteTime: index('availability_exceptions_site_time_idx').on(table.siteId, table.startsAt, table.endsAt) }));
export const bookingSlots = pgTable('booking_slots', { id: uuid('id').defaultRandom().primaryKey(), siteId: uuid('site_id').notNull().references(() => sites.id), serviceId: uuid('service_id').notNull().references(() => bookingServices.id), startsAt: timestamp('starts_at', timestamptz).notNull(), endsAt: timestamp('ends_at', timestamptz).notNull(), timezone: text('timezone').notNull(), status: bookingSlotStatus('status').default('available').notNull(), capacity: integer('capacity').default(1).notNull(), bookedCount: integer('booked_count').default(0).notNull(), createdAt: timestamp('created_at', timestamptz).defaultNow().notNull(), updatedAt: timestamp('updated_at', timestamptz).defaultNow().notNull() }, (table) => ({ slotKey: uniqueIndex('booking_slots_site_service_time').on(table.siteId, table.serviceId, table.startsAt, table.endsAt), availableIndex: index('booking_slots_available_idx').on(table.siteId, table.serviceId, table.startsAt) }));
export const bookings = pgTable('bookings', { id: uuid('id').defaultRandom().primaryKey(), siteId: uuid('site_id').notNull().references(() => sites.id), hostUserId: uuid('host_user_id').notNull().references(() => appUsers.id), serviceId: uuid('service_id').notNull().references(() => bookingServices.id), slotId: uuid('slot_id').references(() => bookingSlots.id), customerName: text('customer_name').notNull(), customerEmail: text('customer_email').notNull(), startsAt: timestamp('starts_at', timestamptz).notNull(), endsAt: timestamp('ends_at', timestamptz).notNull(), timezone: text('timezone').notNull(), status: bookingStatus('status').default('pending').notNull(), externalEventId: text('external_event_id'), notes: text('notes'), legacyPayload: jsonb('legacy_payload').$type<Record<string, unknown>>().notNull().default({}), createdAt: timestamp('created_at', timestamptz).defaultNow().notNull(), updatedAt: timestamp('updated_at', timestamptz).defaultNow().notNull() }, (table) => ({ hostCreatedIndex: index('bookings_host_created_idx').on(table.hostUserId, table.createdAt, table.id), siteTimeIndex: index('bookings_site_time_idx').on(table.siteId, table.startsAt, table.endsAt), activeSlotIndex: index('bookings_active_slot_idx').on(table.slotId) }));
export const bookingIdMap = pgTable('booking_id_map', { legacyBookingId: text('legacy_booking_id').primaryKey(), bookingId: uuid('booking_id').notNull().unique().references(() => bookings.id), createdAt: timestamp('created_at', timestamptz).defaultNow().notNull(), migratedAt: timestamp('migrated_at', timestamptz).defaultNow().notNull() }, (table) => ({ bookingIndex: index('booking_id_map_booking_idx').on(table.bookingId) }));
export const bookingAttendees = pgTable('booking_attendees', { id: uuid('id').defaultRandom().primaryKey(), bookingId: uuid('booking_id').notNull().references(() => bookings.id), role: attendeeRole('role').notNull(), name: text('name').notNull(), email: text('email').notNull(), responseStatus: text('response_status').notNull().default('pending'), createdAt: timestamp('created_at', timestamptz).defaultNow().notNull(), updatedAt: timestamp('updated_at', timestamptz).defaultNow().notNull() });
export const calendarSyncState = pgTable('calendar_sync_state', { id: uuid('id').defaultRandom().primaryKey(), bookingId: uuid('booking_id').notNull().unique().references(() => bookings.id), userId: uuid('user_id').notNull().references(() => appUsers.id), provider: text('provider').notNull(), externalEventId: text('external_event_id'), status: calendarSyncStatus('status').default('pending').notNull(), lastAttemptAt: timestamp('last_attempt_at', timestamptz), syncedAt: timestamp('synced_at', timestamptz), lastError: text('last_error'), createdAt: timestamp('created_at', timestamptz).defaultNow().notNull(), updatedAt: timestamp('updated_at', timestamptz).defaultNow().notNull() }, (table) => ({ providerEvent: uniqueIndex('calendar_sync_provider_event').on(table.provider, table.externalEventId) }));
export const bookingIdempotencyKeys = pgTable('booking_idempotency_keys', { id: uuid('id').defaultRandom().primaryKey(), siteId: uuid('site_id').notNull().references(() => sites.id), requesterUserId: uuid('requester_user_id').references(() => appUsers.id), idempotencyKey: text('idempotency_key').notNull(), requestHash: text('request_hash').notNull(), bookingId: uuid('booking_id').references(() => bookings.id), responseStatus: integer('response_status'), responseBody: jsonb('response_body').$type<Record<string, unknown>>(), expiresAt: timestamp('expires_at', timestamptz).notNull(), createdAt: timestamp('created_at', timestamptz).defaultNow().notNull(), updatedAt: timestamp('updated_at', timestamptz).defaultNow().notNull() }, (table) => ({ siteKey: uniqueIndex('booking_idempotency_site_key').on(table.siteId, table.idempotencyKey), expiry: index('booking_idempotency_expiry_idx').on(table.expiresAt) }));

export const products = pgTable('products', { id: uuid('id').defaultRandom().primaryKey(), legacyProductId: text('legacy_product_id'), legacyPayload: jsonb('legacy_payload').$type<Record<string, unknown>>().notNull().default({}), siteId: uuid('site_id').notNull().references(() => sites.id), creatorUserId: uuid('creator_user_id').notNull().references(() => appUsers.id), slug: text('slug').notNull(), name: text('name').notNull(), description: text('description'), currency: char('currency', { length: 3 }).notNull(), priceMinor: bigint('price_minor', { mode: 'number' }).notNull(), active: boolean('active').default(true).notNull(), providerProductId: text('provider_product_id').unique(), providerPriceId: text('provider_price_id').unique(), createdAt: timestamp('created_at', timestamptz).defaultNow().notNull(), updatedAt: timestamp('updated_at', timestamptz).defaultNow().notNull() }, (table) => ({ siteSlug: uniqueIndex('products_site_slug').on(table.siteId, table.slug), legacyProduct: uniqueIndex('products_legacy_product_idx').on(table.legacyProductId), creatorActive: index('products_creator_active_idx').on(table.creatorUserId, table.active, table.createdAt) }));
export const productVariants = pgTable('product_variants', { id: uuid('id').defaultRandom().primaryKey(), productId: uuid('product_id').notNull().references(() => products.id), sku: text('sku').notNull().unique(), name: text('name').notNull(), optionValues: jsonb('option_values').$type<Record<string, unknown>>().notNull().default({}), priceMinor: bigint('price_minor', { mode: 'number' }), active: boolean('active').default(true).notNull(), createdAt: timestamp('created_at', timestamptz).defaultNow().notNull(), updatedAt: timestamp('updated_at', timestamptz).defaultNow().notNull() }, (table) => ({ productName: uniqueIndex('product_variants_product_name').on(table.productId, table.name) }));
export const inventory = pgTable('inventory', { variantId: uuid('variant_id').primaryKey().references(() => productVariants.id), onHand: integer('on_hand'), reserved: integer('reserved').default(0).notNull(), updatedAt: timestamp('updated_at', timestamptz).defaultNow().notNull() });
export const orders = pgTable('orders', { id: uuid('id').defaultRandom().primaryKey(), legacyOrderId: text('legacy_order_id'), legacyPayload: jsonb('legacy_payload').$type<Record<string, unknown>>().notNull().default({}), creatorUserId: uuid('creator_user_id').notNull().references(() => appUsers.id), siteId: uuid('site_id').notNull().references(() => sites.id), customerEmail: text('customer_email').notNull(), status: orderStatus('status').default('pending_payment').notNull(), state: orderState('state').default('pending').notNull(), fulfillmentStatus: fulfillmentStatus('fulfillment_status').default('unfulfilled').notNull(), providerCheckoutId: text('provider_checkout_id').unique(), idempotencyKey: text('idempotency_key'), totalMinor: bigint('total_minor', { mode: 'number' }).notNull(), currency: char('currency', { length: 3 }).notNull(), createdAt: timestamp('created_at', timestamptz).defaultNow().notNull(), updatedAt: timestamp('updated_at', timestamptz).defaultNow().notNull() }, (table) => ({ creatorCreatedIndex: index('orders_creator_created_idx').on(table.creatorUserId, table.createdAt, table.id), legacyOrder: uniqueIndex('orders_legacy_order_idx').on(table.legacyOrderId), siteIdempotency: uniqueIndex('orders_site_idempotency_idx').on(table.siteId, table.idempotencyKey), stateCreated: index('orders_state_created_idx').on(table.state, table.createdAt) }));
export const orderItems = pgTable('order_items', { id: uuid('id').defaultRandom().primaryKey(), orderId: uuid('order_id').notNull().references(() => orders.id), productId: uuid('product_id').notNull().references(() => products.id), variantId: uuid('variant_id').references(() => productVariants.id), productName: text('product_name').notNull(), quantity: integer('quantity').notNull(), unitPriceMinor: bigint('unit_price_minor', { mode: 'number' }).notNull(), totalMinor: bigint('total_minor', { mode: 'number' }).notNull(), createdAt: timestamp('created_at', timestamptz).defaultNow().notNull(), updatedAt: timestamp('updated_at', timestamptz).defaultNow().notNull() }, (table) => ({ orderIndex: index('order_items_order_idx').on(table.orderId) }));
export const inventoryReservations = pgTable('inventory_reservations', { id: uuid('id').defaultRandom().primaryKey(), productId: uuid('product_id').notNull().references(() => products.id), variantId: uuid('variant_id').references(() => productVariants.id), orderId: uuid('order_id').notNull().references(() => orders.id), quantity: integer('quantity').notNull(), status: reservationStatus('status').default('active').notNull(), expiresAt: timestamp('expires_at', timestamptz).notNull(), idempotencyKey: text('idempotency_key'), releasedAt: timestamp('released_at', timestamptz), consumedAt: timestamp('consumed_at', timestamptz), createdAt: timestamp('created_at', timestamptz).defaultNow().notNull(), updatedAt: timestamp('updated_at', timestamptz).defaultNow().notNull() }, (table) => ({ orderKey: uniqueIndex('inventory_reservations_order_idempotency_idx').on(table.orderId, table.idempotencyKey), expiry: index('inventory_reservations_expiry_idx').on(table.expiresAt) }));
export const inventoryMovements = pgTable('inventory_movements', { id: uuid('id').defaultRandom().primaryKey(), variantId: uuid('variant_id').notNull().references(() => productVariants.id), orderId: uuid('order_id').references(() => orders.id), reservationId: uuid('reservation_id').references(() => inventoryReservations.id), movementType: inventoryMovementType('movement_type').notNull(), quantityDelta: integer('quantity_delta').notNull(), onHandAfter: integer('on_hand_after').notNull(), reservedAfter: integer('reserved_after').notNull(), idempotencyKey: text('idempotency_key').notNull().unique(), reason: text('reason'), createdAt: timestamp('created_at', timestamptz).defaultNow().notNull() }, (table) => ({ variantTime: index('inventory_movements_variant_time_idx').on(table.variantId, table.createdAt), orderIndex: index('inventory_movements_order_idx').on(table.orderId, table.createdAt) }));
export const payments = pgTable('payments', { id: uuid('id').defaultRandom().primaryKey(), orderId: uuid('order_id').notNull().references(() => orders.id), provider: text('provider').default('stripe').notNull(), providerPaymentId: text('provider_payment_id'), providerEventId: text('provider_event_id'), status: paymentStatus('status').default('pending').notNull(), amountMinor: bigint('amount_minor', { mode: 'number' }).notNull(), currency: char('currency', { length: 3 }).notNull(), idempotencyKey: text('idempotency_key').notNull(), rawEvent: jsonb('raw_event').$type<Record<string, unknown>>(), paidAt: timestamp('paid_at', timestamptz), createdAt: timestamp('created_at', timestamptz).defaultNow().notNull(), updatedAt: timestamp('updated_at', timestamptz).defaultNow().notNull() }, (table) => ({ providerPayment: uniqueIndex('payments_provider_payment').on(table.provider, table.providerPaymentId), providerEvent: uniqueIndex('payments_provider_event').on(table.provider, table.providerEventId), providerIdempotency: uniqueIndex('payments_provider_idempotency').on(table.provider, table.idempotencyKey), orderIndex: index('payments_order_idx').on(table.orderId, table.createdAt) }));
export const fulfillments = pgTable('fulfillments', { id: uuid('id').defaultRandom().primaryKey(), orderId: uuid('order_id').notNull().unique().references(() => orders.id), status: fulfillmentState('status').default('unfulfilled').notNull(), trackingNumber: text('tracking_number'), carrier: text('carrier'), shippedAt: timestamp('shipped_at', timestamptz), deliveredAt: timestamp('delivered_at', timestamptz), createdAt: timestamp('created_at', timestamptz).defaultNow().notNull(), updatedAt: timestamp('updated_at', timestamptz).defaultNow().notNull() });
export const subscriptions = pgTable('subscriptions', { id: uuid('id').defaultRandom().primaryKey(), userId: uuid('user_id').notNull().references(() => appUsers.id), provider: text('provider').default('stripe').notNull(), providerCustomerId: text('provider_customer_id'), providerSubscriptionId: text('provider_subscription_id'), providerPriceId: text('provider_price_id'), plan: text('plan').notNull(), status: subscriptionStatus('status').notNull(), entitlementState: entitlementState('entitlement_state').default('free').notNull(), interval: text('interval'), currentPeriodEnd: timestamp('current_period_end', timestamptz), trialEnd: timestamp('trial_end', timestamptz), cancelAt: timestamp('cancel_at', timestamptz), cancelAtPeriodEnd: boolean('cancel_at_period_end').default(false).notNull(), renewedAt: timestamp('renewed_at', timestamptz), createdAt: timestamp('created_at', timestamptz).defaultNow().notNull(), updatedAt: timestamp('updated_at', timestamptz).defaultNow().notNull() }, (table) => ({ userProvider: uniqueIndex('subscriptions_user_provider').on(table.userId, table.provider), providerSubscription: uniqueIndex('subscriptions_provider_subscription').on(table.provider, table.providerSubscriptionId), statusIndex: index('subscriptions_status_idx').on(table.status, table.currentPeriodEnd) }));
export const integrations = pgTable('integrations', { id: uuid('id').defaultRandom().primaryKey(), userId: uuid('user_id').notNull().references(() => appUsers.id), siteId: uuid('site_id').references(() => sites.id), provider: text('provider').notNull(), status: integrationStatus('status').default('disconnected').notNull(), connectionState: text('connection_state').default('connected').notNull(), scopes: text('scopes').array().notNull().default([]), encryptedCredentials: text('encrypted_credentials'), encryptedAccessToken: text('encrypted_access_token'), encryptedRefreshToken: text('encrypted_refresh_token'), tokenExpiresAt: timestamp('token_expires_at', timestamptz), refreshLockUntil: timestamp('refresh_lock_until', timestamptz), tokenVersion: integer('token_version').default(1).notNull(), connectionIdempotencyKey: text('connection_idempotency_key'), revokedAt: timestamp('revoked_at', timestamptz), expiresAt: timestamp('expires_at', timestamptz), lastError: text('last_error'), createdAt: timestamp('created_at', timestamptz).defaultNow().notNull(), updatedAt: timestamp('updated_at', timestamptz).defaultNow().notNull() }, (table) => ({ providerStatus: index('integrations_provider_status_idx').on(table.provider, table.status), connectionIdempotency: uniqueIndex('integrations_connection_idempotency_idx').on(table.connectionIdempotencyKey) }));
export const outboxEvents = pgTable('outbox_events', { id: uuid('id').defaultRandom().primaryKey(), eventType: text('event_type').notNull(), aggregateType: text('aggregate_type').notNull(), aggregateId: uuid('aggregate_id').notNull(), idempotencyKey: text('idempotency_key').notNull(), payload: jsonb('payload').$type<Record<string, unknown>>().notNull().default({}), status: text('status').notNull().default('pending'), attempts: integer('attempts').notNull().default(0), maxAttempts: integer('max_attempts').notNull().default(8), availableAt: timestamp('available_at', timestamptz).defaultNow().notNull(), leaseUntil: timestamp('lease_until', timestamptz), lastError: text('last_error'), publishedAt: timestamp('published_at', timestamptz), createdAt: timestamp('created_at', timestamptz).defaultNow().notNull(), updatedAt: timestamp('updated_at', timestamptz).defaultNow().notNull() }, (table) => ({ idempotencyIndex: uniqueIndex('outbox_events_idempotency_idx').on(table.idempotencyKey), claimIndex: index('outbox_events_claim_idx').on(table.status, table.availableAt, table.createdAt) }));
export const jobStatus = text('status');

export const siteDrafts = pgTable('site_drafts', {
  id: uuid('id').defaultRandom().primaryKey(), accountId: uuid('account_id').notNull().references(() => accounts.id), siteId: uuid('site_id').notNull().references(() => sites.id),
  revision: bigint('revision', { mode: 'number' }).notNull(), status: text('status').notNull().default('draft'), content: jsonb('content').$type<Record<string, unknown>>().notNull().default({}), designConfig: jsonb('design_config').$type<Record<string, unknown>>().notNull().default({}),
  createdBy: uuid('created_by').notNull().references(() => appUsers.id), createdAt: timestamp('created_at', timestamptz).defaultNow().notNull(), updatedAt: timestamp('updated_at', timestamptz).defaultNow().notNull(),
}, (table) => ({ siteRevision: uniqueIndex('site_drafts_site_revision').on(table.siteId, table.revision), siteStatus: index('site_drafts_site_status_idx').on(table.siteId, table.status, table.updatedAt), accountUpdated: index('site_drafts_account_updated_idx').on(table.accountId, table.updatedAt) }));

export const publishedSiteSnapshots = pgTable('published_site_snapshots', {
  id: uuid('id').defaultRandom().primaryKey(), accountId: uuid('account_id').notNull().references(() => accounts.id), siteId: uuid('site_id').notNull().references(() => sites.id), draftId: uuid('draft_id').references(() => siteDrafts.id),
  revision: bigint('revision', { mode: 'number' }).notNull(), content: jsonb('content').$type<Record<string, unknown>>().notNull().default({}), designConfig: jsonb('design_config').$type<Record<string, unknown>>().notNull().default({}), contentHash: text('content_hash').notNull(), publishedBy: uuid('published_by').notNull().references(() => appUsers.id), isCurrent: boolean('is_current').notNull().default(true), createdAt: timestamp('created_at', timestamptz).defaultNow().notNull(), updatedAt: timestamp('updated_at', timestamptz).defaultNow().notNull(),
}, (table) => ({ siteRevision: uniqueIndex('published_snapshots_site_revision').on(table.siteId, table.revision), sitePublished: index('published_snapshots_site_published_idx').on(table.siteId, table.createdAt), accountPublished: index('published_snapshots_account_published_idx').on(table.accountId, table.createdAt) }));

export const siteBlocks = pgTable('site_blocks', {
  id: uuid('id').defaultRandom().primaryKey(), accountId: uuid('account_id').notNull().references(() => accounts.id), siteId: uuid('site_id').notNull().references(() => sites.id), draftId: uuid('draft_id').references(() => siteDrafts.id), snapshotId: uuid('snapshot_id').references(() => publishedSiteSnapshots.id), blockKey: text('block_key').notNull(), blockType: text('block_type').notNull(), position: integer('position').notNull(), config: jsonb('config').$type<Record<string, unknown>>().notNull().default({}), createdAt: timestamp('created_at', timestamptz).defaultNow().notNull(), updatedAt: timestamp('updated_at', timestamptz).defaultNow().notNull(),
}, (table) => ({ draftPosition: uniqueIndex('site_blocks_draft_position').on(table.draftId, table.position), snapshotPosition: uniqueIndex('site_blocks_snapshot_position').on(table.snapshotId, table.position), draftKey: uniqueIndex('site_blocks_draft_key').on(table.draftId, table.blockKey), snapshotKey: uniqueIndex('site_blocks_snapshot_key').on(table.snapshotId, table.blockKey) }));

export const audienceSubscribers = pgTable('audience_subscribers', {
  id: uuid('id').defaultRandom().primaryKey(), accountId: uuid('account_id').notNull().references(() => accounts.id), siteId: uuid('site_id').notNull().references(() => sites.id), email: text('email').notNull(), emailNormalized: text('email_normalized').notNull(), name: text('name'), status: text('status').notNull().default('subscribed'), source: text('source').notNull().default('form'), metadata: jsonb('metadata').$type<Record<string, unknown>>().notNull().default({}), unsubscribedAt: timestamp('unsubscribed_at', timestamptz), deletedAt: timestamp('deleted_at', timestamptz), createdAt: timestamp('created_at', timestamptz).defaultNow().notNull(), updatedAt: timestamp('updated_at', timestamptz).defaultNow().notNull(),
}, (table) => ({ siteEmail: uniqueIndex('audience_subscribers_site_email_idx').on(table.siteId, table.emailNormalized), siteStatus: index('audience_subscribers_site_status_idx').on(table.siteId, table.status, table.createdAt), accountCreated: index('audience_subscribers_account_created_idx').on(table.accountId, table.createdAt) }));

export const formSubmissions = pgTable('form_submissions', {
  id: uuid('id').defaultRandom().primaryKey(), accountId: uuid('account_id').notNull().references(() => accounts.id), siteId: uuid('site_id').notNull().references(() => sites.id), formKey: text('form_key').notNull(), submitterEmail: text('submitter_email'), payload: jsonb('payload').$type<Record<string, unknown>>().notNull().default({}), status: text('status').notNull().default('received'), idempotencyKey: text('idempotency_key').notNull(), processedAt: timestamp('processed_at', timestamptz), retentionUntil: timestamp('retention_until', timestamptz).notNull(), createdAt: timestamp('created_at', timestamptz).defaultNow().notNull(), updatedAt: timestamp('updated_at', timestamptz).defaultNow().notNull(),
}, (table) => ({ siteIdempotency: uniqueIndex('form_submissions_site_idempotency').on(table.siteId, table.idempotencyKey), siteCreated: index('form_submissions_site_created_idx').on(table.siteId, table.createdAt), retention: index('form_submissions_retention_idx').on(table.retentionUntil) }));

export const fulfillmentHistory = pgTable('fulfillment_history', {
  id: uuid('id').defaultRandom().primaryKey(), accountId: uuid('account_id').notNull().references(() => accounts.id), siteId: uuid('site_id').notNull().references(() => sites.id), fulfillmentId: uuid('fulfillment_id').notNull().references(() => fulfillments.id), orderId: uuid('order_id').notNull().references(() => orders.id), previousStatus: fulfillmentState('previous_status'), nextStatus: fulfillmentState('next_status').notNull(), actorUserId: uuid('actor_user_id').references(() => appUsers.id), idempotencyKey: text('idempotency_key').notNull(), metadata: jsonb('metadata').$type<Record<string, unknown>>().notNull().default({}), createdAt: timestamp('created_at', timestamptz).defaultNow().notNull(),
}, (table) => ({ transition: uniqueIndex('fulfillment_history_transition').on(table.fulfillmentId, table.idempotencyKey), order: index('fulfillment_history_order_idx').on(table.orderId, table.createdAt), account: index('fulfillment_history_account_idx').on(table.accountId, table.createdAt) }));

export const oauthConnections = pgTable('oauth_connections', {
  id: uuid('id').defaultRandom().primaryKey(), accountId: uuid('account_id').notNull().references(() => accounts.id), siteId: uuid('site_id').references(() => sites.id), integrationId: uuid('integration_id').references(() => integrations.id), provider: text('provider').notNull(), connectionState: text('connection_state').notNull().default('connected'), scopes: text('scopes').array().notNull().default([]), encryptedAccessToken: text('encrypted_access_token'), encryptedRefreshToken: text('encrypted_refresh_token'), encryptionKeyVersion: integer('encryption_key_version').notNull().default(1), accessTokenExpiresAt: timestamp('access_token_expires_at', timestamptz), refreshLockUntil: timestamp('refresh_lock_until', timestamptz), revokedAt: timestamp('revoked_at', timestamptz), lastError: text('last_error'), connectIdempotencyKey: text('connect_idempotency_key').notNull(), createdAt: timestamp('created_at', timestamptz).defaultNow().notNull(), updatedAt: timestamp('updated_at', timestamptz).defaultNow().notNull(),
}, (table) => ({ scopeProvider: uniqueIndex('oauth_connections_scope_provider').on(table.accountId, table.provider, table.siteId), connectIdempotency: uniqueIndex('oauth_connections_connect_idempotency').on(table.connectIdempotencyKey), refresh: index('oauth_connections_refresh_idx').on(table.connectionState, table.refreshLockUntil, table.accessTokenExpiresAt) }));

export const webhookEvents = pgTable('webhook_events', {
  id: uuid('id').defaultRandom().primaryKey(), provider: text('provider').notNull(), providerEventId: text('provider_event_id').notNull(), eventType: text('event_type').notNull(), status: webhookProcessingStatus('status').default('received').notNull(), payload: jsonb('payload').$type<Record<string, unknown>>().notNull().default({}), attemptCount: integer('attempt_count').notNull().default(0), lastError: text('last_error'), receivedAt: timestamp('received_at', timestamptz).defaultNow().notNull(), processedAt: timestamp('processed_at', timestamptz), updatedAt: timestamp('updated_at', timestamptz).defaultNow().notNull(),
}, (table) => ({ providerEvent: uniqueIndex('webhook_events_provider_event').on(table.provider, table.providerEventId), retry: index('webhook_events_retry_idx').on(table.status, table.receivedAt), type: index('webhook_events_type_idx').on(table.provider, table.eventType, table.receivedAt) }));

export const featureFlags = pgTable('feature_flags', {
  id: uuid('id').defaultRandom().primaryKey(), accountId: uuid('account_id').references(() => accounts.id), siteId: uuid('site_id').references(() => sites.id), flagKey: text('flag_key').notNull(), enabled: boolean('enabled').notNull().default(false), rolloutPercentage: smallint('rollout_percentage').notNull().default(0), config: jsonb('config').$type<Record<string, unknown>>().notNull().default({}), expiresAt: timestamp('expires_at', timestamptz), createdAt: timestamp('created_at', timestamptz).defaultNow().notNull(), updatedAt: timestamp('updated_at', timestamptz).defaultNow().notNull(),
}, (table) => ({ scopeKey: uniqueIndex('feature_flags_scope_key').on(table.accountId, table.siteId, table.flagKey), account: index('feature_flags_account_idx').on(table.accountId, table.flagKey), site: index('feature_flags_site_idx').on(table.siteId, table.flagKey) }));

export const siteSlugRedirects = pgTable('site_slug_redirects', {
  id: uuid('id').defaultRandom().primaryKey(), accountId: uuid('account_id').notNull().references(() => accounts.id), siteId: uuid('site_id').notNull().references(() => sites.id), oldHandle: text('old_handle').notNull(), newHandle: text('new_handle').notNull(), createdBy: uuid('created_by').notNull().references(() => appUsers.id), createdAt: timestamp('created_at', timestamptz).defaultNow().notNull(), updatedAt: timestamp('updated_at', timestamptz).defaultNow().notNull(),
}, (table) => ({ oldHandle: uniqueIndex('site_slug_redirects_old_handle').on(table.oldHandle), site: index('site_slug_redirects_site_idx').on(table.siteId, table.createdAt), target: index('site_slug_redirects_target_idx').on(table.newHandle) }));
